repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
        language_version: python3.6

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.15
    hooks:
    -   id: isort
        language_version: python3.6

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
        additional_dependencies: ["flake8-bugbear == 18.8.0", "flake8-per-file-ignores"]
